### ISSUE TITLE
Adjust Master Task Data

### ISSUE THREAD

**Issue by Allurien** [ffxiv-tracker/ffxiv-tracker#52]
Can we update the following things in the master task data?
- Gold Saucer
  - Rename Mini Catpot to Mini Cactpot
- Beast tribes
  - Change Vath to Gnath
- Challenge Log
  - Turn Crafting and Gathering into two tasks instead of a combined one

**Comment by ginovva320** [comment]
* Custom Deliveries
 * Charlemend

**Comment by ginovva320** [comment]
Added
